CREATE TABLE `pepschedule` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `BATCHID` varchar(20) NOT NULL,
  `S_EQPID` varchar(20) DEFAULT NULL,
  `S_PORT` varchar(4) DEFAULT NULL,
  `S_SLOT` varchar(50) DEFAULT NULL,
  `T_EQPID` varchar(20) DEFAULT NULL,
  `T_PORT` varchar(4) DEFAULT NULL,
  `T_SLOT` varchar(50) DEFAULT NULL,
  `TRAYID` varchar(100) DEFAULT NULL,
  `WORKTYPE` varchar(10) DEFAULT NULL COMMENT '1. O  - OUT\n2. OI - OUT/IN\n3. I    - IN\n4. EI - EMPTY OUT\n5. EO - EMPTY IN\n6. TO - TEST OUT\n7. TI  - TEST IN',
  `EXCUTE_TIME` datetime NOT NULL,
  `STATUS` varchar(10) DEFAULT NULL,
  `LOT_NO` varchar(100) DEFAULT NULL,
  `QTY` varchar(100) DEFAULT NULL,
  `STEPID` varchar(50) DEFAULT NULL,
  `URGENCY` varchar(10) DEFAULT NULL,
  `FLOW_STATUS` varchar(10) DEFAULT NULL,
  `_VEHICLEID` varchar(64) DEFAULT NULL,
  `_bufSlot` varchar(20) DEFAULT NULL,
  `_state` int(11) DEFAULT NULL,
  `_srcAssignTime` datetime DEFAULT NULL,
  `_srcArrivingTime` datetime DEFAULT NULL,
  `_srcStartTime` datetime DEFAULT NULL,
  `_srcFinishTime` datetime DEFAULT NULL,
  `_dstAssignTime` datetime DEFAULT NULL,
  `_dstArrivingTime` datetime DEFAULT NULL,
  `_dstStartTime` datetime DEFAULT NULL,
  `_dstFinishTime` datetime DEFAULT NULL,
  `_isChecked` int(11) DEFAULT NULL,
  `_priority` int(11) DEFAULT NULL,
  `EVENT_DATE` datetime DEFAULT NULL,
  `IF_FLAG` varchar(8) DEFAULT NULL,
  PRIMARY KEY (`ID`,`EXCUTE_TIME`)
) ENGINE=InnoDB AUTO_INCREMENT=175 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `pepschedule_history` (
  `ID` int(11) NOT NULL,
  `BATCHID` varchar(20) NOT NULL,
  `S_EQPID` varchar(20) DEFAULT NULL,
  `S_PORT` varchar(4) DEFAULT NULL,
  `S_SLOT` varchar(50) DEFAULT NULL,
  `T_EQPID` varchar(20) DEFAULT NULL,
  `T_PORT` varchar(4) DEFAULT NULL,
  `T_SLOT` varchar(50) DEFAULT NULL,
  `TRAYID` varchar(100) DEFAULT NULL,
  `WORKTYPE` varchar(10) DEFAULT NULL COMMENT '1. O  - OUT\n2. OI - OUT/IN\n3. I    - IN\n4. EI - EMPTY OUT\n5. EO - EMPTY IN\n6. TO - TEST OUT\n7. TI  - TEST IN',
  `EXCUTE_TIME` datetime NOT NULL,
  `STATUS` varchar(10) DEFAULT NULL,
  `LOT_NO` varchar(100) DEFAULT NULL,
  `QTY` varchar(100) DEFAULT NULL,
  `STEPID` varchar(50) DEFAULT NULL,
  `URGENCY` varchar(10) DEFAULT NULL,
  `_VEHICLEID` varchar(64) DEFAULT NULL,
  `_bufNo` int(11) DEFAULT NULL,
  `_bufSlot` varchar(20) DEFAULT NULL,
  `_state` int(11) DEFAULT NULL,
  `_srcAssignTime` datetime DEFAULT NULL,
  `_srcArrivingTime` datetime DEFAULT NULL,
  `_srcStartTime` datetime DEFAULT NULL,
  `_srcFinishTime` datetime DEFAULT NULL,
  `_dstAssignTime` datetime DEFAULT NULL,
  `_dstArrivingTime` datetime DEFAULT NULL,
  `_dstStartTime` datetime DEFAULT NULL,
  `_dstFinishTime` datetime DEFAULT NULL,
  `_isChecked` int(11) DEFAULT NULL,
  `_priority` int(11) DEFAULT NULL,
  `EVENT_DATE` datetime DEFAULT NULL,
  `IF_FLAG` varchar(8) DEFAULT NULL,
  PRIMARY KEY (`ID`,`EXCUTE_TIME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `vehicle` (
  `idx` int(11) NOT NULL AUTO_INCREMENT,
  `ID` varchar(64) NOT NULL,
  `IP` varchar(20) NOT NULL,
  `port` int(11) NOT NULL,
  `installState` int(11) NOT NULL,
  `_mode` int(11) NOT NULL,
  `_state` int(11) NOT NULL,
  `_loc_x` int(11) DEFAULT NULL,
  `_loc_y` int(11) DEFAULT NULL,
  `_loc_th` int(11) DEFAULT NULL,
  `_chargeRate` float DEFAULT NULL,
  `_BATCHID` varchar(20) DEFAULT NULL,
  `_lastArrivedUnit` varchar(64) DEFAULT NULL,
  `_isMulti` varchar(8) DEFAULT NULL,
  PRIMARY KEY (`idx`,`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `vehicle_part` (
  `idx` int(11) NOT NULL AUTO_INCREMENT,
  `VEHICLEID` varchar(64) NOT NULL,
  `portNo` int(11) NOT NULL,
  `state` int(11) NOT NULL COMMENT 'VehiclePartState(ENABLE(1),DISABLE(0)) 을 설정한다',
  `slotNo` int(11) DEFAULT NULL,
  `_trayId` varchar(25) DEFAULT NULL,
  PRIMARY KEY (`idx`)
) ENGINE=InnoDB AUTO_INCREMENT=45 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `unit` (
  `idx` int(11) NOT NULL AUTO_INCREMENT,
  `ID` varchar(64) NOT NULL,
  `GOALNAME` varchar(64) NOT NULL,
  `goaltype` int(11) NOT NULL,
  `max_col` int(11) DEFAULT NULL,
  `max_row` int(11) DEFAULT NULL,
  `lds_dist` int(11) DEFAULT '0',
  `rf_id` varchar(8) NOT NULL,
  `rf_ch` int(11) NOT NULL,
  `loc_x` int(11) DEFAULT NULL,
  `loc_y` int(11) DEFAULT NULL,
  `direction` varchar(32) DEFAULT NULL,
  `unitcol` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`idx`,`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
