//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPlus
{
    using System;
    using System.Collections.Generic;
    
    public partial class pepschedule_history
    {
        public int ID { get; set; }
        public string MULTIID { get; set; }
        public string BATCHID { get; set; }
        public string S_EQPID { get; set; }
        public string S_PORT { get; set; }
        public string S_SLOT { get; set; }
        public string T_EQPID { get; set; }
        public string T_PORT { get; set; }
        public string T_SLOT { get; set; }
        public string TRAYID { get; set; }
        public string WORKTYPE { get; set; }
        public string TRANSFERTYPE { get; set; }
        public string WINDOW_TIME { get; set; }
        public string EXECUTE_TIME { get; set; }
        public string REAL_TIME { get; set; }
        public string STATUS { get; set; }
        public string LOT_NO { get; set; }
        public string QTY { get; set; }
        public string STEPID { get; set; }
        public string S_STEPID { get; set; }
        public string T_STEPID { get; set; }
        public string URGENCY { get; set; }
        public string FLOW_STATUS { get; set; }
        public string C_VEHICLEID { get; set; }
        public string C_bufSlot { get; set; }
        public Nullable<int> C_state { get; set; }
        public Nullable<System.DateTime> C_srcAssignTime { get; set; }
        public Nullable<System.DateTime> C_srcArrivingTime { get; set; }
        public Nullable<System.DateTime> C_srcStartTime { get; set; }
        public Nullable<System.DateTime> C_srcFinishTime { get; set; }
        public Nullable<System.DateTime> C_dstAssignTime { get; set; }
        public Nullable<System.DateTime> C_dstArrivingTime { get; set; }
        public Nullable<System.DateTime> C_dstStartTime { get; set; }
        public Nullable<System.DateTime> C_dstFinishTime { get; set; }
        public Nullable<int> C_isChecked { get; set; }
        public Nullable<int> C_priority { get; set; }
        public Nullable<int> DOWNTEMP { get; set; }
        public Nullable<System.DateTime> EVENT_DATE { get; set; }
        public Nullable<int> ORDER { get; set; }
    }
}
